version: '2'
services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/opt/{{ project_name }}