# Generated by Django 2.0.5 on 2018-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('sort', models.SmallIntegerField(default=1)),
                ('template', models.CharField(choices=[('default.html', 'default'), ('home.html', 'home')], max_length=100)),
                ('content', models.TextField(blank=True, max_length=10000)),
                ('meta_keywords', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True, max_length=400)),
                ('meta_tags', models.TextField(blank=True, max_length=400)),
                ('scripts', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
